game/characters.rpy
got them to stop talking. also, imported the rest of the posty sprites, and brought in some animation code (which needs work #3 )
=> Stop talking

game/characters.rpy
There is now a clean class-based way for tracking frame-by-frame animations, like Posty's jaw drop.
Fixes #3
=> Somewhat improve frame-by-frame animation code

README.md, game/room001-mainstreet.rpy
https://github.com/pixequil/oso-game-1/assets/49569238/a174369f-00a9-49d7-bf16-a8295cf42c99
Fixes #55
=> Add a description for the butterfly package

game/characters.rpy
Brand Soda is now not as giant.
Fixes #75
=> Resize Brand Soda

README.md
do not remove the blank bullets.
=> brought the credits over

game/defaults.rpy, game/money.rpy, game/room000-start.rpy, game/room001-mainstreet.rpy, game/room003-museum_entrance.rpy, game/room004-museum_blue.rpy, game/room010-dome.rpy, game/toasty_hints.rpy
Separate all defaults into a different file
=> Refactor defaults

game/room001-mainstreet.rpy
Make sure to maintain comments!
=> Remove outdated TODO (#10)

README.md, game/room004-museum_blue.rpy
adds a description for the ladle. closes #43
credit me as Jurta please 😁
=> add ladle description

README.md, game/room010-dome.rpy
initial dialogue. this is the first actual scene to be added so i'll remind everyone that you're welcome to make comments if you think there should be changes to this conversation.
https://github.com/pixequil/oso-game-1/blob/b22f00753a8d909f5e9a4cc11515ec2c93a0fc7b/game/room010-dome.rpy#L43-L61
=> bonbon & sour gummy dialogue by BumpBob Looly

game/characters.rpy
Toasty now finally leaves the developer room
https://github.com/pixequil/oso-game-1/assets/49569238/770d47e6-1032-4714-82c6-980bf9f0cb10
Fixes #93
=> Fix Toasty and Cameron not leaving the scene

game/characters.rpy
=> Change Toasty's text colour to `#BE2533`

game/characters.rpy
Instead of using `states.toasty.reset()`, you have to use `states.toasty.no_anim()` as that's more intuitive.
=> Refactor some animation code

game/toasty_hints.rpy
adds the "full ladle" hint. fixes #51
if there's anything that i need to change, i'll have to do it tomorrow as i've got to go to sleep now 😅
in case i also need to state it here, i'd like to be credited as Jurta
=> add full ladle hint

game/characters.rpy
https://github.com/pixequil/oso-game-1/assets/49569238/3706c238-1e56-49b5-ad09-eaa0cccca765
Fixes #97
=> Animate BT Net's swaying

game/money.rpy, game/room001-mainstreet.rpy
also rearranges some of the posty-showing logic wherever relevant.
=> add bs encounters

game/toasty_hints.rpy
=> remove erroneous lines (where did these come from)

game/characters.rpy
=> sample security cameron text color from sprite

README.md
i guess this is common practice?
=> move credit to top

game/room001-mainstreet.rpy
Players could think the black screen is a loading screen.
=> Fix black screen at beginning of game

game/options.rpy
Text will now appear at 30 characters / sec.
https://github.com/pixequil/oso-game-1/assets/49569238/8fda7469-3a6c-4275-9f8f-e6b7d6e5f5bf
=> Make text appear letter-by-letter

game/characters.rpy
B.T Net now sways less and a little faster.
https://github.com/pixequil/oso-game-1/assets/49569238/7597b471-9c37-4403-b423-9c068d61f6ca
=> Change B.T Net's swaying speed

README.md
This will make me sleep at night.
=> More README nitpicking

game/money.rpy, game/room001-mainstreet.rpy, game/room002-musicstore.rpy, game/room009-alley.rpy, game/room010-dome.rpy, game/room011-park.rpy
=> 315 main street navigation remembers your last spot

game/room003-museum_entrance.rpy
cameron "Hey."
cameron "..."
cameron "Did you need something?"
p "Oh. No. Just… checking in. Seeing what's up."
cameron "'What's up'? My blood pressures what's up!" cameron "Just kidding I don't think I have that."
p "..."
p "Right."
cameron "Just come back to me if something broth-ers you. I mean bothers you." cameron "Bye."
p "Bye."
=> p "Hey man."

README.md, game/defaults.rpy, game/money.rpy, game/room001-mainstreet.rpy, game/toasty_hints.rpy
Feedback on added dialogue would be cool.
If you want to add any jokes of your own, feel free!
=> Brand soda quest dialogue

game/toasty_hints.rpy
Toasty gives a hint if you made retainer leave and you haven't talked to crayon box
=> 292-toasty-hint-if-retainer-leaves-and-haven't-talked-to-crayon-box

game/room004-museum_blue.rpy
Blue Tile comes after painting is stolen (doesn't know Posty stole it)
=> blue-tile-after-painting-stolen

game/room007-janitors.rpy
=> 240-generi-chips-description

game/defaults.rpy, game/money.rpy, game/room001-mainstreet.rpy, game/room002-musicstore.rpy, game/room003-museum_entrance.rpy, game/toasty_hints.rpy, game/trophy.rpy
#46, #47 , #48, #49, #53, #54, #53, #293
=> Main Street Dialogs

game/room001-mainstreet.rpy
It works! Added miso soup conversation before any soup was taken
=> Added Miso Soup conversation before any soup was taken

game/room003-museum_entrance.rpy
=> Rewrote easel Narration

game/room004-museum_blue.rpy
=> added #118, #121 and #127

game/room003-museum_entrance.rpy, game/toasty_hints.rpy
#254 #257 #256 #30 #128 and other convos with Security Cameron (.inspiration)
=> Museum Entrance Dialogue

game/room004-museum_blue.rpy
Credit to funnyboy044, @CONKINGTON, and @f4nimator  for writing #40 #114 #123 #34 #119 #366
=> Dialogue Update for 40-114-123-34-119-366

game/room004-museum_blue.rpy
Credit to Fanimator, funnyboy044, Satomi, and XKZ
=> Blue exhibit dialogue

game/room006-museum_food.rpy
=> Base Marble Interaction

game/room011-park.rpy
Added the Posty Nap Conversation
=> Added posty nap conversation

game/defaults.rpy, game/room001-mainstreet.rpy, game/room004-museum_blue.rpy, game/room005-museum_war.rpy, game/toasty_hints.rpy
=> Queue pass 1

game/room006-museum_food.rpy, game/toasty_hints.rpy
Don't merge these yet, I'm working through these
=> queue pass 2

game/room003-museum_entrance.rpy, game/room009-alley.rpy
=> tag interaction with the notice

README.md, game/room001-mainstreet.rpy
=> 50-miso-soup-convo

game/defaults.rpy, game/room011-park.rpy
#287 
also made it so you can only interact with retainer once to fit the text (he says he's going home)
=> Dialogue for #287

game/toasty_hints.rpy
i have done my assinged written part between toasty and posty
=> 420 Writing Task Done

README.md, game/defaults.rpy, game/money.rpy, game/room005-museum_war.rpy, game/room006-museum_food.rpy, game/room007-janitors.rpy, game/room009-alley.rpy, game/room011-park.rpy, game/toasty_hints.rpy
closes #221
closes #222 
closes #229 
closes #163 
closes #172  
closes #208 
closes #209 
closes #210 
closes #401
closes #407 
closes #373 
closes #120
closes #245 
closes #287
=> Last Writing Pass

README.md
Just changes to the readme file
=> Added missing people to readme file

game/room005-museum_war.rpy
=> scanter quest red and blue
